version: '3'

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  www:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=prod
    labels:
      - traefik.backend=proxy
      - traefik.frontend.rule=Host:proxy.vaayadi.in
      - traefik.docker.network=proxy
      - traefik.port=8080
    networks:
      - internal
      - proxy